apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8000
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP