apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-tls-secret
  namespace: {{.Release.Namespace}}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.webhook.tls.certificate }}
  tls.key: {{ .Values.webhook.tls.key }}